spring:
  datasource:
    url: jdbc:mysql://localhost:3306/websystique
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp